---

- name: BIGIP F5 Azure LTM Base - General settings
  bigip_sys_global:
    state: present
    banner_text: |-
      ====================================================
      Give a man a program, frustrate him for a day.
      Teach a man to program, frustrate him for a lifetime
      ====================================================
    console_timeout: 0
    gui_setup: no
    mgmt_dhcp: no
    net_reboot: no
    quiet_boot: yes
    security_banner: yes
    provider: "{{ f5_provider }}"
  delegate_to: localhost
