---
# tasks file for f5_bigip_az_ltm

- name: Role - F5 BIGIP Azure LTM Base
  block:
    #- import_tasks: ntp.yml
    #- import_tasks: monitors.yml
    #- import_tasks: nodes.yml
    #- import_tasks: pools.yml
    - import_tasks: data_groups.yml
    #- import_tasks: irules.yml
    #- import_tasks: ssl_profiles.yml
    - import_tasks: virtual_servers.yml
